services:
  backend:
    container_name: mean-food-store-backend
    image: alexjr2002/food-store-backend:prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/src/.env
    ports:
      - "3000:3000"

  frontend:
    container_name: mean-food-store-frontend  
    image: alexjr2002/food-store-frontend:prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "4000:4000"