# backend-chart/values.yaml
replicaCount: 1

image:
  repository: paulatrujillo/mean-food-store-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

env:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hbGV4YW5kZXJzYW5jaGV6anI6Z0FNVzh3SUdJOTlJNVRFbUBmb29kLXN0b3JlLWNsdXN0ZXIuYTBoZmtocy5tb25nb2RiLm5ldC9mb29kLXN0b3JlLWRiP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPWZvb2Qtc3RvcmUtY2x1c3Rlcgo=
  JWT_SECRET: c2VjcmV0Cg==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVA5NmtHUnJncTlSMGNhRDRwSmxRTmhZb053WGZ4VXVrekg0Y1ZrdmdvUDNRQW9qbTlRMEJqNUtOTWNYWnhsZFgySHpmWm9uUVgzWW5xeDBjSFA5NzluVzAwbk55OXZ4dkQK

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}