name: Docker Images CI

on:
  push:
    branches: 
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Backend Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend  # Context remains the same (current directory)
          file: ./backend/Dockerfile  # Dynamic Dockerfile path
          push: true  # Enable pushing the image
          tags: ${{ secrets.DOCKER_USERNAME }}/food-store-backend-test:latest  # Separate tags for services
      - name: Run Frontend Tests
        run: cd frontend && npm run test
      - name: Build Docker Frontend Image
        run: |
          docker build \
          --build-arg SERVER_URL="http://localhost:3000/api" \
          --build-arg FOODS_PATH="/foods" \
          --build-arg TAGS_PATH="/tags" \
          --build-arg SEARCH_PATH="/search" \
          --build-arg LOGIN_PATH="/users/login" \
          --build-arg REGISTER_PATH="/users/register" \
          --build-arg ORDER_PATH="/orders" \
          --build-arg CREATE_ORDER_PATH="/orders/create" \
          --build-arg NEW_ORDER_FOR_CURRENT_USER_PATH="/orders/newOrderForCurrentUser" \
          --build-arg PAY_ORDER_PATH="/orders/pay" \
          --build-arg STRIPE_KEY=${{ secrets.STRIPE_KEY }} \
          --build-arg IS_PRODUCTION=true \
          -t alexjr2002/food-store-frontend:prod \
          -f ./frontend/Dockerfile .
      - name: Push Docker Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/food-store-frontend:v.1
        
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
