name: Docker Image CI

on:
  push:
    branches: [ "ci-test" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]  # Define services to build images for
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./  # Context remains the same (current directory)
          file: ./${{ matrix.service }}/Dockerfile  # Dynamic Dockerfile path
          push: true  # Enable pushing the image
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}-ci:latest  # Separate tags for services
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
